### ISSUE TITLE
how to use callback?

### ISSUE THREAD

**Issue by Miss-violet** [mumuy/widget#10]
如何调用callback函数？
现在有个需求是：搜索模块中，点击重置按钮，下拉框要重置选项。

**Comment by mumuy** [comment]
callback是事件接口，不是方法接口……表示数据获取时触发，而不是你去调用

**Comment by Miss-violet** [comment]
能不能举个例子：
我有一个下拉框，选项分别是：“请选择”、“1-1”、“1-2”，对应的value是：“”、“1-1”、“1-2”。
正常情况下，页面初始化后选中项是“请选择”，我能不能在页面初始化的时候，传值给这个下拉框，让它默认选中项是“1-1”？
可以的话，该怎么写呢？

**Comment by mumuy** [comment]
下拉框和搜索提示是不同的组件，插件是开源，但是真没办法帮写代码

**Comment by Miss-violet** [comment]
嗯，是这样子的，下拉框的callback(api)参数是setValue，就是这个setValue，我一直没弄明白要怎么用..

**Comment by mumuy** [comment]
setValue 就是只能设置值，没有初始化样式……初始化只能在页面开始加载的时候，多select，options节点设置啊

**Comment by mumuy** [comment]
和原生一样，原生怎么布局就怎么初始化啊，选中哪个就option selected选项

**Comment by haguo2008** [comment]
城市联动有一个问题，直辖市与省份同级，但在城市级变了区级，淘宝ip数据库的直辖市是city级的。问题就来了，例如php获取'city'直是重庆市 在城市联动匹配$_POST["city"]匹配不到了.能否直辖市和特别行政区在城市级重复一次显示。谢谢

**Comment by mumuy** [comment]
我的逻辑和淘宝的逻辑不一样，为什么要修改我的呢？本身就是独立的两个产品啊

而且城市联动插件支持city是重庆市啊
如：
$('#demo').citys({valueType:'name',city:'重庆',area:'巴南'});
是可以选中“重庆市巴南区”的！

**Comment by haguo2008** [comment]
我想这样能显示直辖市
`<select name="city""><option value="重庆" data-code="500000">重庆市</option></select>`
貌似不支持在name="city"选项下显示直辖市和特别行政区,你给的demo直辖市是在name="province"省级显示的

**Comment by mumuy** [comment]
这个做不到！
如果你的重庆在<select name="city"">里面，那么我点击它要切换的时候还能不能看到“福建省”？
你应该在后端自己判断

**Comment by haguo2008** [comment]
嗯,谢谢！这也只能在后端判断了。

**Comment by 307god** [comment]
有些不甚理解，callback(api)中的setValue该如何在外部使用？

**Comment by mumuy** [comment]
@307god 目前只能拿一个外部变量存起来了，其他没想到好的方式

**Comment by 307god** [comment]
@mumuy 那我是不是可以这么理解，当一个插件被定义之后，无法去改变其中的某一个值？

**Comment by mumuy** [comment]
@307god 不是啊，我是说你可以把API存起来调用

**Comment by 307god** [comment]
@mumuy 看来是我没动0.0，大佬可否随手写个例子，学习一下_(:з」∠)_

**Comment by mumuy** [comment]
@307god 项目演示本身就是DEMO啊

**Comment by 307god** [comment]
以tabs为例，里面几个例子都是每次将插件的参数初始化了，而我的想法是对于已经初始化的插件我只改变其属性中的一个参数，其中的属性不被初始化的默认属性覆盖
