### ISSUE TITLE
有关三级联动的“请选择”的小建议

### ISSUE THREAD

**Issue by SadPencil** [mumuy/widget#12]
`<option value="" selected disabled style="display: none;"> - 请选择 - </option>`
这种写法可以让用户未选择时，具有required属性的select依然会发挥作用，而不是把“请选择”当成一个选项。而且用户一旦选择后，“请选择”就会消失。
比`<option value=""> - 请选择 - </option>`要好。

**Comment by mumuy** [comment]
不准备接受，抱歉了～
