### ISSUE TITLE
三级联动初始化完成以后不能使用jq动态的修该内容吗

### ISSUE THREAD

**Issue by JorgeLiu** [mumuy/widget#16]
城市三级联动不能ajax请求后在使用$("#city_field_s").citys({code: content.city});这样修改吗?前面已经定义好了,会报错Uncaught TypeError: $(...).citys is not a function

**Comment by mumuy** [comment]
不理解你要表达什么

**Comment by erastudio** [comment]
和我的需求类似，就是说初始化通过 code 设定了一个 省市区的渲染。

能否在别处ajax后回来的code值重新触发选中这个组件的省市区选项。

**Comment by mumuy** [comment]
可以啊，但是我不能告诉你怎么做，这并不是插件本身的问题
