### ISSUE TITLE
文件夹传到/usr/plugins目录下，后台看不到启动的选项呢？？

### ISSUE THREAD

**Issue by hyy34** [mumuy/widget#19]
![1](https://user-images.githubusercontent.com/26433019/37756089-2454429a-2de3-11e8-9949-af2ed4910048.jpg)
![2](https://user-images.githubusercontent.com/26433019/37756090-2492761e-2de3-11e8-84ba-def1a437c655.jpg)

**Comment by mumuy** [comment]
什么是启动的选项？？？我这个是jQuery插件，不是wordpress插件啊
