### ISSUE TITLE
请问地区编码如何转换为地区名显示出来呢？

### ISSUE THREAD

**Issue by yjl118** [mumuy/widget#20]
例如：注册时选择了地区，数据库里保存了地区编码，然后在资料页想要显示用户数据中地区编码所对应的地区名称，最好是P标签方式。

**Comment by yjl118** [comment]
已参照着示例写出来了

**Comment by yjl118** [comment]
参照着示例三，把值直接传入到citys里，倒是可以通过ID显示了，但遇上地区编码为数组时又没办法了。
有没有简单点的方法？例如{data['area']['code']}直接就转换为对应的地区名。
`$('#demo2').citys({
code:地区编码,
    onChange:function(data){
    $('#demo2').text(data['area']);
    }
});`

**Comment by mumuy** [comment]
其实，不明白你说什么
地区码为什么是数组，一直都是6位的数字啊
