### ISSUE TITLE
郵政編碼好像有問題

### ISSUE THREAD

**Issue by zivhsiao** [mumuy/widget#21]
您好
我發現這個郵政編碼，可能不正確

350000 福建 是正確
440000 廣東 正確是 510000
510000 四川 正確是 610000

好像有一些對，我還沒清楚去對

**Comment by mumuy** [comment]
这不是邮政编码啊！这是行政区划代码。。。。

**Comment by mumuy** [comment]
我重来没说过这是邮政编码
