### ISSUE TITLE
哥们，这个三级联动可不可以写成通用的

### ISSUE THREAD

**Issue by askme-gpt** [mumuy/widget#22]
我现在需求是课程种类-》课程等级-》课程单元-》课程某一课；是这样的四个等级，课程种类下面有很多种，数学课，语文课，英语课，语文课下面很多个等级，level 1,level 2...，level下面有很多unit,unit1，unit2..，unit下就是lesson1,lesson2...我需要把我的数据变成什么样的才可以使用你这个多级联动呢？如果你把这个写成通用的，那就更棒了！别人想用只需要把数据组合成和你一致的格式，就可以直接套用。

**Comment by flygirl0313** [comment]
可以写成哦~   这是一开始写的demo，那时候还没有想封装组件的想法！！ 可以写一个

**Comment by flygirl0313** [comment]
可以写成哦~   这是一开始写的demo，那时候还没有想封装组件的想法！！ 可以写一个

**Comment by andyChenAn** [comment]
这个应该还是在于你的数据结构是怎么样的，如果结构一致，肯定是可以的，我之前也写过一个地区选择组件，也是用作者的地区数据，我是将地区数据解析，并重新生成一个json数据，今后不管是什么样的数据只要结构一样，都是可以实现类似功能的

**Comment by askme-gpt** [comment]
现在的这个数据结构和我们常用的不一样，其实我有国家信息这个sql，一个表格就搞定了。我给你看看我们的数据结构。后端很多都是用这个数据库。对于联动的很方便。

```
DROP TABLE IF EXISTS `area`;
CREATE TABLE `area` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `parent_area_id` int(11) unsigned DEFAULT '0' COMMENT '父ID',
  `level` tinyint(3) unsigned DEFAULT '0' COMMENT '层级',
  `path` varchar(16) DEFAULT '' COMMENT '路径',
  `phone_code` varchar(8) DEFAULT '' COMMENT '国家电话区号',
  `timezone` varchar(32) DEFAULT NULL COMMENT '时差',
  `chinese_name` varchar(64) DEFAULT '' COMMENT '中文名称',
  `english_name` varchar(64) DEFAULT '' COMMENT '英文名称',
  `iso2` varchar(16) DEFAULT '' COMMENT 'ISO标准国家代码2个大写字母',
  `iso3` varchar(16) DEFAULT '' COMMENT '国家缩写',
  `iso_numeric` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '国家代码(ISO 3166-1 numeric)',
  `geo_name_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '根据这个id可以在geonames.org上获取经纬度信息',
  `pinyin` varchar(64) DEFAULT '' COMMENT '中文拼音',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4170 DEFAULT CHARSET=utf8 COMMENT='全球地区库，采集自腾讯QQ国内+国际版.ADD.JENA.20141221';

```
这里粘贴不了图片呢。直接把sql放这里，你可以下载直接导入。
链接: https://pan.baidu.com/s/1nK_wE_sKuAXHfWhr44FQhw 密码: jnt4

**Comment by andyChenAn** [comment]
@ShuiPingYang 那你可以将地区数据解析成和课程种类一样的格式就行啊。
{
    "语文" : {
        "语文level1" : ["unit1" , "unit2" , "unit3"],
        "语文level2" : ["unit4" , "unit5" , "unit6"],
        "语文level3" : ["unit7" , "unit8" , "unit9"]
    },
    "数学" : {
        "数学level1" : ["lesson1" , "lesson2" , "lesson3"]
    }
}
这是我将课程的内容写成这种json格式，因为我自己写的哪个地区选择器就是将地区解析为这种格式，直接放进去可以使用，不过我这里只做了三级联动，没有做第四级联动。
这是我自己写的，https://github.com/andyChenAn/components/tree/master/components/select 你可以看你一下，写的不好，不要见怪啊，你可以把分支clone下来，里面有例子

**Comment by mumuy** [comment]
这是你的需求，并不是我的工作，我做的就是行政区划

**Comment by mumuy** [comment]
有想法挺好的，你可以自己去拓展做，但是我不做这方面的
