### ISSUE TITLE
不能使用

### ISSUE THREAD

**Issue by 1094549944** [mumuy/widget#26]
下载的zip 包不能使用，文件加载不上

**Comment by mumuy** [comment]
你看下是不是路径问题，文件的

**Comment by 1094549944** [comment]
> 你看下是不是路径问题，文件的

不是路径的问题，我看到，提供的demo 也不能使用，在查看网页源码的时候，发现和下载下来的包没有什么不同。

**Comment by mumuy** [comment]
我的在线Demo可以正常工作啊！说明肯定是使用方法不对
