### ISSUE TITLE
城市三级联动里面的直辖市无法绑定赋值

### ISSUE THREAD

**Issue by TANSHUAI1001** [mumuy/widget#3]
$('.citys').citys({province:'',city:'天津市',area:'静海区'}); 显示 天津市，无法显示区。
$('.citys').citys({province:'天津市',city:'静海区',area:''}); 显示 天津市和平区。
$('.citys').citys({province:'天津市',city:'',area:'静海区'}); 显示 天津市和平区。

**Comment by mumuy** [comment]
谢谢指出～已修复，兼容这三种写法
