### ISSUE TITLE
amd/cmd 定义多了jquery

### ISSUE THREAD

**Issue by sidealice** [mumuy/widget#7]
原来的：
    if (typeof define === "function" && (define.amd || define.cmd) && !jQuery) {
我改为：
    if (typeof define === "function" && (define.amd || define.cmd) ) {

就没有jquery 未定义的错误了。

**Comment by mumuy** [comment]
不是多了，我故意加的……

**Comment by sidealice** [comment]
加了为什么会报错呢？ 我看了其他类库没有这一部分，依赖在requirejs里面定义的。

**Comment by mumuy** [comment]
为了防止别人用requirejs，而jquery又是全局引用的……你是怎么用的呢？if(!jQuery){}不管有没有jQuery判断都不会出错才是啊
